### ISSUE TITLE
kook机器人能够收到消息，但无法回复消息，能帮忙看看是啥原因吗

### ISSUE THREAD

**Issue by huoshuigege** [H4rry217/AimRobot-kookbot#1]
![image](https://github.com/H4rry217/AimRobot-kookbot/assets/107799621/73bc4d42-a4b5-42c4-b0b8-85ea826f665e)
机器人可以接收命令 但消息无法回复 麻烦看一下原因  谢谢

**Comment by H4rry217** [comment]
https://github.com/orgs/simple-robot/discussions/181
